### ISSUE TITLE
Reported mapping counts between ontologies are inconsistent and higher than the actual counts

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_linked_data#115]
For example, the reported number of mappings between MONDO and DOID is significantly higher than the actual number:

<img width="1404" alt="Screen Shot 2021-03-13 at 12 29 40 PM" src="https://user-images.githubusercontent.com/2042070/111043566-11e0b800-83f8-11eb-95e1-0c381fdc85de.png">

The real number of mappings between MONDO and DOID is **7825**.

The mapping counts reported are frequently not reciprocal between two ontologies. For example:

DOID Ontology
---------------
<img width="1471" alt="Screen Shot 2021-03-13 at 12 45 14 PM" src="https://user-images.githubusercontent.com/2042070/111043938-65ec9c00-83fa-11eb-9502-03508c00f7cd.png">

NIFSTD Ontology
------------------
<img width="1521" alt="Screen Shot 2021-03-13 at 12 44 53 PM" src="https://user-images.githubusercontent.com/2042070/111043937-6422d880-83fa-11eb-8518-b6f0af962c93.png">

The real number of mappings between DOID and NIFSTD is **19552**.

**Comment by graybeal** [comment]
This problem is no longer an issue for these two ontologies, thanks to the work recently done on #115. The number of mappings from DOID -> NIFSTD and from NIFSTD -> DOID are both 17735, and that matches the number shown in the pop-up windows (344 pages @ 50 per page + 35 on the last page), and the numbers shown at http://data.bioontology.org/mappings/statistics/ontologies/DOID and http://data.bioontology.org/mappings/statistics/ontologies/NIFSTD.

I'm not sure on what basis the 'real number of mappings' is listed as 19552; I suspect that includes a significant number of duplicates which were also eliminated during the recent changes.

**Comment by mdorf** [comment]
The script that used to generate mapping counts had a bug that used graphs from multiple submissions of the same ontology to generate mappings, resulting in duplicates. The bug is now fixed, so the mapping counts are generated only between the latest submissions of ontologies.
