### ISSUE TITLE
intermittent TestMapping#test_mappings_rest failures

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_linked_data#180]
Frequent intermittent unit test failures `TestMapping#test_mappings_rest` 

```
  1) Failure:
TestMapping#test_mappings_rest [/srv/ontoportal/ontologies_linked_data/test/models/test_mappings.rb:289]:
Expected: 3
  Actual: 4
```

failure usually goes away when unit test is re-run

**Comment by syphax-bouazzouni** [comment]
I confirm also, that this behavior hasn't real the time to fix it before.

I assume the issue is related to our implementation of the mapping tests which are order dependent.  

For example this action  https://github.com/ncbo/ontologies_linked_data/actions/runs/6727861859/job/18286309240 failed  with test_mappings_rest returning 4 where expected 3.  So I think if you use the seed 20774 by adding the option `--seed 20774` when running tests (got from the log of the action) you should reproduce the failing test, locally.
