### ISSUE TITLE
SKOS ontologies appear with NO root classes

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_linked_data#82]
There appears to be a bug in the BioPortal OWL API Wrapper that prevents SKOS ontologies' root classes from being correctly identified. As a result, the roots endpoint shows an empty set, resulting in a variety of abnormal behavior with the ontology.

Examlpe:
http://data.bioontology.org/ontologies/FAST-EVENT-SKOS/classes/roots

This issue is related to: https://github.com/ncbo/bioportal-project/issues/36

**Comment by jvendetti** [comment]
Complete list of SKOS ontologies where the roots endpoint returns an empty set:

http://data.bioontology.org/ontologies/DCTERMS/classes/roots
http://data.bioontology.org/ontologies/FAST-EVENT-NT/classes/roots
http://data.bioontology.org/ontologies/FAST-EVENT-SKOS/classes/roots
http://data.bioontology.org/ontologies/FAST-FORMGENRE/classes/roots
http://data.bioontology.org/ontologies/FAST-TITLE/classes/roots
http://data.bioontology.org/ontologies/FAST-TOPICAL/classes/roots
http://data.bioontology.org/ontologies/ISO19115ROLES/classes/roots
http://data.bioontology.org/ontologies/LCGFT/classes/roots
http://data.bioontology.org/ontologies/LCMPT/classes/roots
http://data.bioontology.org/ontologies/PLACES/classes/roots

Note that I left a very few ontologies off this list that were private and clearly uploaded only for testing purposes. The list above is the set of SKOS ontologies that appear to be legitimate contributions from end users.

**Comment by jonquet** [comment]
Hello. @antool and me have created an issue here to capture BioPortal related SKOS enhancements:
https://github.com/agroportal/agroportal_web_ui/issues/19

Indeed skos:topConcept is mandatory

**Comment by jvendetti** [comment]
After investigating SKOS support in BioPortal to address this issue, I'd like to offer the following clarifications:

1. The definition of what constitutes a SKOS vocabulary is quite loose. BioPortal properly returns root concepts via the "roots" endpoint, but only for vocabularies that contain certain SKOS constructs. I've put up a [wiki page](https://www.bioontology.org/wiki/index.php/SKOSSupport) with the necessary documentation to educate the BioPortal community about what sort of SKOS vocabularies we're currently able to support.

2. There are no bugs in the [owlapi_wrapper](https://github.com/ncbo/owlapi_wrapper) project with regard to identification of root concepts, as indicated in the initial comment. The code that determines the set of root concepts for SKOS vocabularies is on the Ruby side (see the "roots" method, beginning on [this line](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L1334)).

3. None of the SKOS vocabularies listed in the [second comment](https://github.com/ncbo/ontologies_linked_data/issues/82#issuecomment-339844726) contain the necessary SKOS constructs (skos:hasTopConcept assertions) that the current code base expects in order to retrieve the set of roots.

I propose that we close this particular issue, and instead enter specific enhancement requests for broadening our handling of SKOS vocabularies. For example, we could enhance the code that calculates the set of roots to use other methodologies besides querying for hasTopConcept assertions (e.g., a SPARQL query that looks for all concepts with narrower concepts, but no broader concepts).

**Comment by jvendetti** [comment]
I'm marking this as "won't fix" status and closing. I think there's been general agreement in the group that we will only handle a certain subset of SKOS vocabularies that have the particular construct that allows our current system to return a set of root classes (explained in detail on [this wiki page](https://www.bioontology.org/wiki/SKOSSupport#skos:ConceptScheme_.26_skos:hasTopConcept)).
